syntax on
set nu rnu
set ignorecase smartcase
set title
set hls is
hi Visual cterm=reverse ctermbg=0
hi Comment ctermfg=238
hi Search ctermfg=0

set cursorcolumn
hi CursorColumn ctermbg=233

" Automatically deletes all trailing whitespace and newlines at end of file on save.
	autocmd BufWritePre * %s/\s\+$//e
	autocmd BufWritepre * %s/\n\+\%$//e

set ai
"set tabstop=2
"set shiftwidth=2
"set expandtab
"set ruler
